import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "None"
opacity = 0.92
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10

[font]
size = 20

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "BoldItalic"

[env]
TERM = "xterm-256color"
