-- local overseer = require("overseer")
-- 
-- overseer.register_template({
--     name = "TypeScript Compile & Run",
--     builder = function()
--         return {
--             cmd = "tsc && node dist/index.js",
--             components = { "default" },
--         }
--     end,
--     condition = {
--       filetype = { "typescript" },
--     },
-- })
-- 
-- vim.keymap.set("n", "<leader>tr", function()
--     overseer.run_template("TypeScript Compile & Run")
-- end, { desc = "Compile and run TypeScript" })
